[[redirects]]
  from = "/"
  to = "https://github.com/Akku-Craft"
  status = 302

[[redirects]]
  from = "/wiki"
  to = "https://github.com/Akku-Craft/wiki/wiki"
  status = 302

[[redirects]]
  from = "/github"
  to = "https://github.com/Akku-Craft"
  status = 302
